#!/bin/bash

ENV=$1
DEVICE_ID=$(ifconfig eth0 |grep HWaddr |tr -s ' ' |cut -d ' ' -f 5 | tr -d ':')

case "$ENV" in
    "test")
        URL="http://api.hive.test.bigboards.io/api/v1/devices/${DEVICE_ID}"
        ;;
    *)
        if [ "x" = "${ENV}x" ]; then
            URL="http://api.hive.bigboards.io/api/v1/devices/${DEVICE_ID}"
        else
            URL="http://${ENV}/api/v1/devices/${DEVICE_ID}"
        fi
        ;;
esac


FIRMWARE=$(dpkg -l bigboards-mmc |grep bigboards-mmc | tr -s ' ' |cut -d ' ' -f 3)
IPV4=$(ifconfig eth0 |grep "inet addr:" | tr -s ' ' |cut -d ' ' -f 3 |cut -d ':' -f2)
ARCH=$(uname -m)
MEMORY=$(cat /proc/meminfo |grep MemTotal |tr -s ' ' |cut -d ' ' -f 2)

TMPFILE=$(mktemp /tmp/temporary-file.XXXXXXXX)

cat > ${TMPFILE} << EOF
[
    { "op": "set", "fld": "firmware", "val": "${FIRMWARE}" },
    { "op": "set", "fld": "ipv4", "val": "${IPV4}" },
    { "op": "set", "fld": "arch", "val": "${ARCH}" },
    { "op": "set", "fld": "memory", "val": "${MEMORY}" }
]
EOF

# Update the Hosted Zone record
curl -H 'Content-Type: application/json' -X PATCH -d "@${TMPFILE}" $URL
