- name: install mandatory tooling
  apt: name="{{ item }}" state="present"
  with_items:
    - "curl"
    - "python-pip"
    - "python-urllib3"
    - "python-dev"
    - "build-essential"
    - "apt-transport-https"

- name: instal python libraries
  pip:
   name: "{{ item }}"
   state: present
  with_items:
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"

- name: create the bb group
  group:
    name: bigboards
    system: yes
    state: present

- name: create the bb user
  user:
    name: bb
    group: bigboards
    system: yes
    state: present